<?php

namespace hanneskod\readmetester\DependencyInjection;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\DependencyInjection\Exception\InvalidArgumentException;
use Symfony\Component\DependencyInjection\Exception\LogicException;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;
use Symfony\Component\DependencyInjection\ParameterBag\FrozenParameterBag;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class ProjectServiceContainer extends Container
{
    protected $parameters = [];

    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMap = [
            'application' => 'getApplicationService',
        ];

        $this->aliases = [];
    }

    public function compile(): void
    {
        throw new LogicException('You cannot compile a dumped container that was already compiled.');
    }

    public function isCompiled(): bool
    {
        return true;
    }

    public function getRemovedIds(): array
    {
        return [
            'Crell\\Tukio\\OrderedProviderInterface' => true,
            'Fig\\EventDispatcher\\AggregateProvider' => true,
            'Psr\\Container\\ContainerInterface' => true,
            'Psr\\EventDispatcher\\EventDispatcherInterface' => true,
            'Symfony\\Component\\DependencyInjection\\ContainerInterface' => true,
            'default_configuration' => true,
            'hanneskod\\readmetester\\Attributes\\AppendCode' => true,
            'hanneskod\\readmetester\\Attributes\\Assert' => true,
            'hanneskod\\readmetester\\Attributes\\Example' => true,
            'hanneskod\\readmetester\\Attributes\\ExampleContext' => true,
            'hanneskod\\readmetester\\Attributes\\ExpectError' => true,
            'hanneskod\\readmetester\\Attributes\\ExpectOutput' => true,
            'hanneskod\\readmetester\\Attributes\\Ignore' => true,
            'hanneskod\\readmetester\\Attributes\\IgnoreError' => true,
            'hanneskod\\readmetester\\Attributes\\IgnoreOutput' => true,
            'hanneskod\\readmetester\\Attributes\\IgnoreUnmarkedExamples' => true,
            'hanneskod\\readmetester\\Attributes\\Import' => true,
            'hanneskod\\readmetester\\Attributes\\Isolate' => true,
            'hanneskod\\readmetester\\Attributes\\Name' => true,
            'hanneskod\\readmetester\\Attributes\\NamespaceName' => true,
            'hanneskod\\readmetester\\Attributes\\PrependCode' => true,
            'hanneskod\\readmetester\\Attributes\\StartInHtmlMode' => true,
            'hanneskod\\readmetester\\Attributes\\StartInPhpNamespace' => true,
            'hanneskod\\readmetester\\Attributes\\UseClass' => true,
            'hanneskod\\readmetester\\Attributes\\UseConst' => true,
            'hanneskod\\readmetester\\Attributes\\UseFunction' => true,
            'hanneskod\\readmetester\\CliConsole' => true,
            'hanneskod\\readmetester\\Compiler\\CodeBlockImportingPass' => true,
            'hanneskod\\readmetester\\Compiler\\CompilerFactoryFactory' => true,
            'hanneskod\\readmetester\\Compiler\\CompilerFactoryInterface' => true,
            'hanneskod\\readmetester\\Compiler\\FileInput' => true,
            'hanneskod\\readmetester\\Compiler\\MultipassCompiler' => true,
            'hanneskod\\readmetester\\Compiler\\StdinInput' => true,
            'hanneskod\\readmetester\\Compiler\\TransformationPass' => true,
            'hanneskod\\readmetester\\Compiler\\UniqueNamePass' => true,
            'hanneskod\\readmetester\\Config\\ArrayRepository' => true,
            'hanneskod\\readmetester\\Config\\ConfigManager' => true,
            'hanneskod\\readmetester\\Config\\Configs' => true,
            'hanneskod\\readmetester\\Config\\DefaultConfigFactory' => true,
            'hanneskod\\readmetester\\Config\\UserConfigRepository' => true,
            'hanneskod\\readmetester\\Config\\YamlRepository' => true,
            'hanneskod\\readmetester\\Event\\BootstrapIncluded' => true,
            'hanneskod\\readmetester\\Event\\ConfigurationIncluded' => true,
            'hanneskod\\readmetester\\Event\\DebugEvent' => true,
            'hanneskod\\readmetester\\Event\\ExampleEntered' => true,
            'hanneskod\\readmetester\\Event\\ExampleExited' => true,
            'hanneskod\\readmetester\\Event\\ExampleIgnored' => true,
            'hanneskod\\readmetester\\Event\\ExampleSkipped' => true,
            'hanneskod\\readmetester\\Event\\ExecutionStarted' => true,
            'hanneskod\\readmetester\\Event\\ExecutionStopped' => true,
            'hanneskod\\readmetester\\Event\\ExitStatusListener' => true,
            'hanneskod\\readmetester\\Event\\FileIncluded' => true,
            'hanneskod\\readmetester\\Event\\LogEvent' => true,
            'hanneskod\\readmetester\\Event\\TestFailed' => true,
            'hanneskod\\readmetester\\Event\\TestPassed' => true,
            'hanneskod\\readmetester\\Event\\TestingAborted' => true,
            'hanneskod\\readmetester\\ExampleTester' => true,
            'hanneskod\\readmetester\\Example\\ArrayExampleStore' => true,
            'hanneskod\\readmetester\\Example\\CombinedExampleStore' => true,
            'hanneskod\\readmetester\\Example\\ExampleObj' => true,
            'hanneskod\\readmetester\\Expectation\\ErrorExpectation' => true,
            'hanneskod\\readmetester\\Expectation\\ExpectationEvaluator' => true,
            'hanneskod\\readmetester\\Expectation\\Failure' => true,
            'hanneskod\\readmetester\\Expectation\\OutputExpectation' => true,
            'hanneskod\\readmetester\\Expectation\\Success' => true,
            'hanneskod\\readmetester\\FilesystemInputGenerator' => true,
            'hanneskod\\readmetester\\Input\\Definition' => true,
            'hanneskod\\readmetester\\Input\\Markdown\\MarkdownCompilerFactory' => true,
            'hanneskod\\readmetester\\Input\\Markdown\\Parser' => true,
            'hanneskod\\readmetester\\Input\\ParserInterface' => true,
            'hanneskod\\readmetester\\Input\\ParsingCompiler' => true,
            'hanneskod\\readmetester\\Input\\Template' => true,
            'hanneskod\\readmetester\\Input\\TemplateRenderer' => true,
            'hanneskod\\readmetester\\Output\\DebugOutputtingSubscriber' => true,
            'hanneskod\\readmetester\\Output\\DefaultOutputtingSubscriber' => true,
            'hanneskod\\readmetester\\Output\\JsonOutputtingSubscriber' => true,
            'hanneskod\\readmetester\\Output\\VoidOutputtingSubscriber' => true,
            'hanneskod\\readmetester\\Runner\\BootstrapFactory' => true,
            'hanneskod\\readmetester\\Runner\\ErrorOutcome' => true,
            'hanneskod\\readmetester\\Runner\\EvalRunner' => true,
            'hanneskod\\readmetester\\Runner\\OutputOutcome' => true,
            'hanneskod\\readmetester\\Runner\\ProcessRunner' => true,
            'hanneskod\\readmetester\\Runner\\RunnerFactory' => true,
            'hanneskod\\readmetester\\Runner\\SkippedOutcome' => true,
            'hanneskod\\readmetester\\Runner\\VoidOutcome' => true,
            'hanneskod\\readmetester\\Utils\\CodeBlock' => true,
            'hanneskod\\readmetester\\Utils\\Instantiator' => true,
            'hanneskod\\readmetester\\Utils\\Loader' => true,
            'hanneskod\\readmetester\\Utils\\NameObj' => true,
            'hanneskod\\readmetester\\Utils\\Regexp' => true,
        ];
    }

    /**
     * Gets the public 'application' shared autowired service.
     *
     * @return \Symfony\Component\Console\SingleCommandApplication
     */
    protected function getApplicationService()
    {
        $this->services['application'] = $instance = new \Symfony\Component\Console\SingleCommandApplication();

        $a = new \hanneskod\readmetester\ExampleTester(new \hanneskod\readmetester\Expectation\ExpectationEvaluator());

        $b = new \Fig\EventDispatcher\AggregateProvider();

        $c = new \hanneskod\readmetester\Utils\Instantiator();

        $d = new \Crell\Tukio\OrderedListenerProvider($c);

        $e = new \hanneskod\readmetester\Event\ExitStatusListener();

        $d->addListener($e);

        $b->addProvider($d);

        $f = new \Crell\Tukio\Dispatcher($b);

        $a->setEventDispatcher($f);
        $g = new \hanneskod\readmetester\Compiler\CompilerFactoryFactory();
        $g->setInstantiator($c);
        $h = new \hanneskod\readmetester\FilesystemInputGenerator();
        $h->setEventDispatcher($f);
        $i = new \hanneskod\readmetester\Runner\RunnerFactory();
        $i->setInstantiator($c);
        $j = new \hanneskod\readmetester\Runner\BootstrapFactory();
        $j->setEventDispatcher($f);

        $k = new \hanneskod\readmetester\CliConsole(new \hanneskod\readmetester\Config\ConfigManager((new \hanneskod\readmetester\Config\DefaultConfigFactory())->createRepository()), $a, $g, $e, $h, $i, $j, $d);
        $k->setEventDispatcher($f);

        $instance->setName('Readme-Tester');
        $instance->setVersion('dev');
        $instance->setCode($k);
        $k->configure($instance);

        return $instance;
    }
}
